name: Firebase Deploy

on:
  push:
    branches:
      - main  # Or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Or your Node.js version
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build the app
        run: npm run build  # Replace with your build command (e.g., npm run build, yarn build)
      - name: Deploy to Firebase
        uses: wzieba/firebase-github-action@v2
        with:
          args: deploy --only hosting
          token: ${{ secrets.FIREBASE_TOKEN }}
